# Record gateway VM names and address in /etc/hosts
# Gateways are special PITA because we don't have control over whatever it is assigning the IP address.
# It's probably a DHCP server on a multi-function router installed by an ISP.
# Luckily we know the MAC address.
# Use tricks with nmap and arp to discover each gateway IP adddresses.
# Create an entry in /etc/hosts like these.
#   192.168.1.83   gateway.home   gateway
# We need these because Ansible can't SSH to the private lab interface.
# SSH works for all the other VMs by sneakily going via the public interface,
# but the confused routing prevents that on these multi-interface gateway VMs.
#
# It's a good idea to do more admin.
# * Fix the IPv4 address in the DHCP server, so IP won't change in future.
# * Add these entries to /etc/hosts on the workstation.

# !!! use a virsh command to extract IP: 
#     virsh domifaddr --source agent gateway.silvan.uk | grep enp1s0 | awk '{print $4}'
#     virsh qemu-agent-command gateway.silvan.uk '{"execute":"guest-network-get-interfaces"}' | jq .return[1]
# !!! qemu-guest-agent is probably already running.
# !!! https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10/html-single/configuring_and_managing_linux_virtual_machines/index#enabling-qemu-guest-agent-on-linux-guests
# 

- name: Discover
  # ansible.builtin.include_tasks: nmap_scan.yml
  ansible.builtin.include_tasks: domifaddr.yml
- name: Update
  ansible.builtin.include_tasks: update_etc_hosts.yml
