
- name: Set facts
  ansible.builtin.set_fact:
      line_public: "{{ ipv4_for_nic0 }}   {{ build_hostname + '.' + build_home_domain }}   {{ build_hostname + 'public' }}"
      line_private: "{{ build_install_config['nics'][1]['ip'] }}   {{ build_install_config['fqdn'] }}   {{ build_hostname  + 'private' }}"

# add on managed node
- name: "Add /etc/hosts: {{ line_public }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # search_string: "{{ hosts_record_conf['fqdn'] }}"
    line: "{{ line_public }}"

- name: "Add /etc/hosts: {{ line_private }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # search_string: "{{ hosts_record_conf['fqdn'] }}"
    line: "{{ line_private }}"

# add on control node
- name: "Add /etc/hosts: {{ line_public }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # search_string: "{{ hosts_record_conf['fqdn'] }}"
    line: "{{ line_public }}"
  delegate_to: localhost

- name: "Add /etc/hosts: {{ line_private }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    # search_string: "{{ hosts_record_conf['fqdn'] }}"
    line: "{{ line_private }}"
  delegate_to: localhost

